export const AUTHENTICATED = "AUTHENTICATED"
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
export const SUCCESSFULLY_LOADED_ACCOUNTS = "SUCCESSFULLY_LOADED_ACCOUNTS"
export const UNSUCCESSFULLY_LOADED_ACCOUNTS = "UNSUCCESSFULLY_LOADED_ACCOUNTS"